-- Seed: Insert 8 code-audit challenges from MockChallengeRepository
-- Idempotent: uses DO $$ ... ON CONFLICT DO NOTHING ... END $$ blocks

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-sqli', 'SQL Injection en Login', 'Este endpoint de login es vulnerable a SQL Injection. La entrada del usuario se concatena directamente en la consulta SQL sin sanitizar. Un atacante puede manipular el parámetro username para ejecutar comandos SQL arbitrarios.', 'junior', 'security', 'typescript', 'https://github.com/example/vulnerable-api', 'import { db } from ''./database'';\n\nexport async function login(username: string, password: string) {\n  const query = `SELECT * FROM users WHERE username = ''${username}'' AND password = ''${password}''`;\n  const user = await db.execute(query);\n\n  if (user.rows.length > 0) {\n    return { success: true, token: generateToken(user.rows[0]) };\n  }\n\n  return { success: false };\n}', 'SQL Injection', 'available', '2025-01-01T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-xss', 'XSS en Comentarios', 'Este componente renderiza comentarios de usuarios directamente con innerHTML, sin sanitizar. Un usuario malicioso puede inyectar scripts arbitrarios que se ejecutarán en el navegador de otros usuarios.', 'junior', 'security', 'typescript', 'https://github.com/example/social-app', 'import { Component, Input } from ''@angular/core'';\n\n@Component({\n  selector: ''comment-thread'',\n  template: ''<div [innerHTML]="renderComment()"></div>''\n})\nexport class CommentThread {\n  @Input() comments: Comment[] = [];\n\n  renderComment(): string {\n    return this.comments\n      .map(c => `<div class="comment">${c.body}</div>`)\n      .join('''');\n  }\n}', 'Cross-Site Scripting', 'available', '2025-01-02T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-god', 'Diosidad / Cyclomatic Complexity', 'Esta función handlePayment procesa TODOS los tipos de pago en un solo bloque. Tiene complejidad ciclomática altísima, mezcla responsabilidades y es imposible de testear por separado. Cualquier cambio en un método de pago puede romper los otros.', 'mid', 'design', 'typescript', 'https://github.com/example/payment-service', 'async function handlePayment(order: Order, method: string, data: any) {\n  if (method === ''credit_card'') {\n    const validated = validateCard(data.cardNumber, data.cvv, data.expiry);\n    if (!validated) throw new Error(''Invalid card'');\n    const charged = await chargeCard(data.cardNumber, order.total);\n    if (!charged) { await notifyFailure(order.userId); return false; }\n    await sendEmail(order.userId, ''payment-ok'');\n    await updateInventory(order.items);\n    return true;\n  } else if (method === ''paypal'') {\n    const token = await getPaypalToken(data.code);\n    const executed = await executePaypal(token, order.total);\n    if (!executed) { await logError(''paypal'', order.id); return false; }\n    await sendEmail(order.userId, ''payment-ok'');\n    return true;\n  } else if (method === ''crypto'') {\n    const tx = await blockchainTransaction(data.wallet, order.total);\n    await waitForConfirmations(tx.hash, 3);\n    await sendEmail(order.userId, ''payment-ok'');\n    return true;\n  } else if (method === ''transfer'') {\n    const bankRef = data.bankRef;\n    await verifyTransfer(bankRef, order.total);\n    await sendEmail(order.userId, ''payment-ok'');\n    await sendEmail(order.userId, ''invoice'', { ref: bankRef });\n    return true;\n  }\n  throw new Error(''Unsupported payment method'');\n}', 'God Function', 'available', '2025-01-03T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-callback', 'Callback Hell / Promesas Anidadas', 'Esta función procesa un usuario nuevo con una cadena de callbacks anidados. Es ilegible, difícil de debuggear, y cualquier error en un paso intermedio deja el sistema en un estado inconsistente porque no hay manejo de errores.', 'junior', 'async', 'typescript', 'https://github.com/example/user-service', 'function createUser(email: string, password: string, callback: (err?: Error) => void) {\n  validateEmail(email, (err) => {\n    if (err) return callback(err);\n    hashPassword(password, (err, hash) => {\n      if (err) return callback(err);\n      db.query(''INSERT INTO users (email, password) VALUES ($1, $2)'', [email, hash], (err) => {\n        if (err) return callback(err);\n        sendWelcomeEmail(email, (err) => {\n          if (err) return callback(err);\n          logAudit(''user-created'', email, () => {\n            callback();\n          });\n        });\n      });\n    });\n  });\n}', 'Callback Hell', 'available', '2025-01-04T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-mutation', 'Mutación de Props en Componentes', 'Este componente hijo muta directamente la propiedad recibida del padre. En Angular, los @Input no deben modificarse internamente. Esto causa efectos secundarios impredecibles y bugs intermitentes difíciles de rastrear.', 'junior', 'angular', 'typescript', 'https://github.com/example/angular-app', 'import { Component, Input } from ''@angular/core'';\n\n@Component({\n  selector: ''user-list'',\n  template: `\n    <div *ngFor="let user of users">\n      {{ user.name }}\n      <button (click)="deleteUser(user)">Delete</button>\n    </div>\n  `\n})\nexport class UserListComponent {\n  @Input() users: User[] = [];\n\n  deleteUser(target: User) {\n    const index = this.users.indexOf(target);\n    if (index > -1) {\n      this.users.splice(index, 1); // MUTATING THE INPUT!\n    }\n  }\n}', 'Prop Mutation', 'available', '2025-01-05T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-dead', 'Código Muerto / Condiciones Redundantes', 'Esta función está llena de condiciones que nunca se cumplen, branches inalcanzables, y variables que se asignan pero nunca se usan. El código muerto aumenta la carga cognitiva y sugiere que hubo refactors incompletos.', 'junior', 'logic', 'typescript', 'https://github.com/example/legacy-codebase', 'function calculateDiscount(price: number, type: string): number {\n  let discount = 0;\n  const TAX_RATE = 0.21;\n  const result = price * TAX_RATE;\n\n  if (type === ''none'') return 0;\n  if (type === ''seasonal'') {\n    discount = price * 0.2;\n  } else if (type === ''loyalty'') {\n    discount = price * 0.15;\n  } else if (type === ''clearance'') {\n    discount = price * 0.5;\n  } else if (type === ''vip'') {\n    discount = price * 0.3;\n  } else if (type === ''employee'') {\n    discount = price * 0.4;\n  } else {\n    discount = price * 0.1;\n  }\n\n  if (price > 1000) {\n    const extra = 50;\n    discount += extra;\n    return discount;\n  }\n\n  // This never executes if price > 1000\n  if (discount > price * 0.8) {\n    return price * 0.8;\n  }\n\n  return discount;\n}', 'Dead Code', 'available', '2025-01-06T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-errors', 'Falta de Manejo de Errores', 'Esta función asume que todas las operaciones asíncronas van a funcionar perfectamente. No hay try/catch, no hay validación de respuestas, no hay manejo de errores de red. Si la API falla, el usuario ve una pantalla en blanco sin explicación.', 'junior', 'error-handling', 'typescript', 'https://github.com/example/dashboard-app', 'import { Component, OnInit } from ''@angular/core'';\n\n@Component({\n  selector: ''app-dashboard'',\n  template: `\n    <h1>Welcome {{ user.name }}</h1>\n    <div *ngFor="let item of items">{{ item.name }}</div>\n  `\n})\nexport class DashboardComponent implements OnInit {\n  user: any;\n  items: any[] = [];\n  dashboardStats: any;\n\n  async ngOnInit() {\n    const userResp = await fetch(''/api/user'');\n    this.user = await userResp.json();\n\n    const itemsResp = await fetch(''/api/items'');\n    this.items = await itemsResp.json();\n\n    const stats = await fetch(''/api/stats'');\n    this.dashboardStats = await stats.json();\n  }\n}', 'Silent Failures', 'available', '2025-01-07T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;

DO $$ BEGIN
    INSERT INTO public.challenges (id, title, description, difficulty, category, language, repo_url, code, code_smell, status, created_at)
    VALUES ('ch-naming', 'Variables con Naming Opaco', 'Esta función usa nombres de variables crípticos que obligan al lector a hacer ingeniería inversa para entender qué hace cada cosa. En un código profesional, el nombre de una variable debe revelar su intención sin necesidad de comentarios.', 'junior', 'readability', 'typescript', 'https://github.com/example/obfuscated-code', 'function calc(a: number, b: number, c: string): number {\n  const d = new Date();\n  const e = d.getFullYear() - a;\n  const f = e * 12 + b;\n\n  let g = 0;\n  for (let i = 0; i < f; i++) {\n    const h = c === ''monthly'' ? 1 : c === ''yearly'' ? 12 : 0;\n    const j = f - i;\n    const k = 0.05 / 12;\n    const l = Math.pow(1 + k, j);\n    const m = k * l / (l - 1);\n    g += h * m;\n  }\n\n  const n = g * a / 100;\n  return Math.round(n * 100) / 100;\n}', 'Poor Naming', 'available', '2025-01-08T00:00:00Z')
    ON CONFLICT (id) DO NOTHING;
END $$;